name: 'last-successful-build-action'
description: 'Action to find the sha of the last successful workflow of a branch.'
branding:
  icon: rewind
  color: blue
inputs:
  token:
    description: 'GITHUB_TOKEN.'
    default: ${{ github.token }}
    required: true
  branch:
    description: 'Branch for the workflow to look for.'
    required: true
  workflow:
    description: 'Workflow name to look for.'
    required: false
  verify:
    description: 'Verify SHA of workflow run commit against list of commit SHAs in repository'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: './tools/last-successfull-build/main.js'
